name: pratice
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.1
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
